# DM
#  v.
- key: "vmmc-8-v-1-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND (date('now')-date(efm.dob))<1
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-1-9-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 1<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=9
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-10-14-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 10<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=14
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-15-19-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 15<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=19
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-20-24-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 20<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=24
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-25-29-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 25<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=29
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-30-34-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 30<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=34
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-35-39-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 35<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=39
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-40-44-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 40<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=44
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-45-49-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND 45<=(date('Now')-date(efm.dob))  AND (date('Now')-date(efm.dob))<=49
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"

- key: "vmmc-8-v-50-dm"
  description: "VMMC number of male circumcised who returned for followup visit"
  indicatorQuery: " SELECT count(DISTINCT evn.entity_id) as count FROM ec_vmmc_follow_up_visit evn
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evn.entity_id
  INNER JOIN ec_vmmc_procedure vp ON vp.entity_id = evn.entity_id
  WHERE evn.id =(SELECT MAX(id)  FROM ec_vmmc_follow_up_visit)
  AND 7 < ((julianday('now') - julianday(substr(followup_visit_date, 7, 4) || '-'
  || substr(followup_visit_date, 4, 2) || '-'
  || substr(followup_visit_date, 1, 2))) BETWEEN 0 AND 7)
  AND male_circumcision_method = 'device'
  AND (date('now')-date(efm.dob))>=50
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evn.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
