indicators:
  - key: "vmmc-1-1-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
WHERE   (date('now')-date(efm.dob))<1
AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-1-9-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
WHERE (date(efm.dob, '+1 years') <= date('now'))
AND (date(efm.dob, '+10 years') > date('now'))
AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-10-14-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE   (date(efm.dob, '+10 years') <= date('now'))
AND (date(efm.dob, '+15 years') > date('now'))
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-15-19-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE (date(efm.dob, '+15 years') <= date('now'))
AND (date(efm.dob, '+20 years') > date('now'))
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-20-24-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE (date(efm.dob, '+20 years') <= date('now'))
AND (date(efm.dob, '+25 years') > date('now'))
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-25-29-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE  (date(efm.dob, '+25 years') <= date('now'))
AND (date(efm.dob, '+30 years') > date('now'))
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-30-34-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE (date(efm.dob, '+30 years') <= date('now'))
AND (date(efm.dob, '+35 years') > date('now'))
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-35-39-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE (date(efm.dob, '+35 years') <= date('now'))
AND (date(efm.dob, '+40 years') > date('now'))
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-40-44-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE (date(efm.dob, '+40 years') <= date('now'))
AND (date(efm.dob, '+45 years') > date('now'))
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-45-49-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE (date(efm.dob, '+45 years') <= date('now'))
AND (date(efm.dob, '+50 years') > date('now'))
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"
  - key: "vmmc-1-50-a"
    description: "Jumla ya wateja wa VMMC"
    indicatorQuery: " SELECT count(DISTINCT evc.id) as count FROM ec_vmmc_confirmation evc
  INNER JOIN ec_family_member efm ON efm.base_entity_id = evc.id
  WHERE   (date('now')-date(efm.dob))>=50
  AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
  date(substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||'-' ||
  substr(strftime('%Y-%m-%d', datetime(evc.last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) ||'-' || '01')"